name: theses
version: 1
handle:

- compress: if ( out_header["Content-type"] ~ "application/javascript" ) compress
- compress: if ( out_header["Content-type"] ~ "text/css" ) compress
- compress: if ( out_header["Content-type"] ~ "text/javascript" ) compress